// Package witai is a free speech-to-text engine backed by Wit.ai. A Wit app is
// single-language, so one key is embedded per supported language.
package witai

import (
	"encoding/json"
	"sort"
	"sync"

	"github.com/paradoxe35/encre/internal/logger"
)

// Set by keys_embedded.go, generated by scripts/embed-witai-keys.sh from WITAI_KEYS at build time.
var rawKeys = ""

type Key struct {
	Token    string `json:"key"`
	Language string `json:"lang"`
}

// A constructor so tests can rebind rawKeys and get a fresh cache instead of sync.OnceValue's
// permanent one.
func newParseKeys() func() []Key {
	return sync.OnceValue(func() []Key {
		if rawKeys == "" {
			return nil
		}

		var keys []Key
		if err := json.Unmarshal([]byte(rawKeys), &keys); err != nil {
			logger.Warn("Could not parse embedded Wit.ai keys", "error", err)
			return nil
		}

		valid := make([]Key, 0, len(keys))
		for _, k := range keys {
			if k.Token != "" && k.Language != "" {
				valid = append(valid, k)
			}
		}
		return valid
	})
}

var parseKeys = newParseKeys()

func Available() bool {
	return len(parseKeys()) > 0
}

func Languages() []string {
	keys := parseKeys()
	langs := make([]string, 0, len(keys))
	for _, k := range keys {
		langs = append(langs, k.Language)
	}
	sort.Strings(langs)
	return langs
}

func tokenFor(lang string) (string, bool) {
	for _, k := range parseKeys() {
		if k.Language == lang {
			return k.Token, true
		}
	}
	return "", false
}
