#ifndef ENCRE_FFI_H
#define ENCRE_FFI_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define encre_SAMPLE_RATE 16000

typedef void *encre_ClipboardHandle;

typedef void *encre_HotkeyManagerHandle;

/**
 * Receives the action string the binding was registered with.
 */
typedef void (*encre_HotkeyCallback)(const char*);

/**
 * Push-to-talk delivers both edges: 1 when the key goes down, 0 when it comes
 * up. Kept separate from `HotkeyCallback` so existing bindings keep their ABI.
 */
typedef void (*encre_PttCallback)(const char*, int);

typedef void *encre_SimulatorHandle;

typedef void *encre_SttHandle;

/**
 * Reports microphone level while recording, so the host can draw a meter.
 */
typedef void (*encre_LevelCallback)(float);

#if defined(ENCRE_MACOS)
extern bool CGEventSourceKeyState(int32_t state_id, uint16_t key);
#endif

/**
 * Returns the last error as a C string (free with `encre_free_string`), or NULL if none.
 */
const char *encre_get_last_error(void);

/**
 * Frees a string returned by any function in this crate.
 */
void encre_free_string(char *s);

encre_ClipboardHandle encre_clipboard_new(void);

/**
 * Null when the clipboard holds no text, including when it holds an image.
 */
char *encre_clipboard_get_text(encre_ClipboardHandle handle);

/**
 * 1 when the clipboard holds text, 0 when not. Distinguishes "copied a picture" from
 * "the copy never landed", which look identical through `get_text`.
 */
int encre_clipboard_has_text(encre_ClipboardHandle handle);

int encre_clipboard_set_text(encre_ClipboardHandle handle, const char *text);

/**
 * Empties the clipboard, so a following simulated copy landing becomes observable.
 */
int encre_clipboard_clear(encre_ClipboardHandle handle);

int encre_clipboard_save(encre_ClipboardHandle handle);

int encre_clipboard_restore(encre_ClipboardHandle handle);

void encre_clipboard_free(encre_ClipboardHandle handle);

encre_HotkeyManagerHandle encre_hotkey_manager_new(void);

int encre_hotkey_clear(encre_HotkeyManagerHandle handle);

int encre_hotkey_register(encre_HotkeyManagerHandle handle,
                          const char *binding,
                          const char *action,
                          encre_HotkeyCallback callback);

/**
 * Registers a push-to-talk binding. The callback receives 1 on key down and 0
 * on key up, so the host can record only while the shortcut is held.
 */
int encre_hotkey_register_hold(encre_HotkeyManagerHandle handle,
                               const char *binding,
                               const char *action,
                               encre_PttCallback callback);

int encre_hotkey_start(encre_HotkeyManagerHandle handle);

int encre_hotkey_stop(encre_HotkeyManagerHandle handle);

/**
 * Null when the listener is running. The caller frees the string with `encre_free_string`.
 */
char *encre_hotkey_listen_error(encre_HotkeyManagerHandle handle);

void encre_hotkey_manager_free(encre_HotkeyManagerHandle handle);

encre_SimulatorHandle encre_simulator_new(void);

int encre_simulate_select_all(encre_SimulatorHandle handle);

int encre_simulate_copy(encre_SimulatorHandle handle);

int encre_simulate_paste(encre_SimulatorHandle handle);

/**
 * Releases modifiers still held from the triggering hotkey. Call once before any combo.
 */
int encre_simulate_release_modifiers(encre_SimulatorHandle handle);

void encre_simulator_free(encre_SimulatorHandle handle);

encre_SttHandle encre_stt_new(encre_LevelCallback level);

void encre_stt_free(encre_SttHandle handle);

/**
 * Loads a model and keeps it resident. Idempotent for the same path, so the
 * host may call it on every dictation.
 */
int encre_stt_load(encre_SttHandle handle, const char *path);

int encre_stt_unload(encre_SttHandle handle);

int encre_stt_start(encre_SttHandle handle);

/**
 * Stops recording and transcribes. Blocks for as long as inference takes, so
 * the host must call it off its UI thread.
 */
char *encre_stt_stop(encre_SttHandle handle);

int encre_stt_cancel(encre_SttHandle handle);

/**
 * Transcribes a 16 kHz mono WAV without touching the microphone, so a model
 * can be verified from settings.
 */
char *encre_stt_transcribe_file(encre_SttHandle handle, const char *path);

/**
 * Selects the capture device by name. Null or empty means the system default.
 * Takes effect on the next recording.
 */
int encre_stt_set_device(encre_SttHandle handle, const char *name);

/**
 * Sets the spoken language as an ISO code; NULL or empty asks the model to
 * detect, which only some can.
 */
int encre_stt_set_language(encre_SttHandle handle, const char *code);

/**
 * Enables or disables capture-only mode: while on, recording never touches the
 * engine, so `encre_stt_stop` fails and audio must be read back with
 * `encre_stt_stop_pcm`. Takes effect on the next recording.
 */
int encre_stt_set_capture_only(encre_SttHandle handle, bool enabled);

/**
 * Stops a capture-only recording and returns the audio as headerless 16-bit
 * signed little-endian PCM, mono, at `encre_SAMPLE_RATE`. Free with
 * `encre_stt_free_bytes`. Null on failure; a silent take returns a valid
 * zero-length buffer.
 */
uint8_t *encre_stt_stop_pcm(encre_SttHandle handle, uintptr_t *out_len);

/**
 * Frees a buffer returned by `encre_stt_stop_pcm`.
 */
void encre_stt_free_bytes(uint8_t *ptr, uintptr_t len);

/**
 * Input device names, newline separated, the default marked with a leading '*'.
 */
char *encre_stt_devices(void);

#endif  /* ENCRE_FFI_H */
