#ifndef ENCRE_FFI_H
#define ENCRE_FFI_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(ENCRE_MACOS)
/**
 * Stamped on every event the simulator posts, so the hotkey listener can tell them from the
 * user's own keystrokes.
 */
#define encre_SYNTHETIC_TAG 1162756946
#endif

#define encre_SAMPLE_RATE 16000

typedef void *encre_ClipboardHandle;

typedef void *encre_HotkeyManagerHandle;

/**
 * Receives the action string the binding was registered with.
 */
typedef void (*encre_HotkeyCallback)(const char*);

/**
 * Receives the action string and 1 on key down, 0 on key up.
 */
typedef void (*encre_PttCallback)(const char*, int);

typedef void *encre_SimulatorHandle;

typedef void *encre_SttHandle;

/**
 * Microphone RMS level while recording, for a meter.
 */
typedef void (*encre_LevelCallback)(float);

/**
 * Null when there is no error. Free with `encre_free_string`.
 */
const char *encre_get_last_error(void);

/**
 * Frees a string returned by any function in this crate.
 */
void encre_free_string(char *s);

encre_ClipboardHandle encre_clipboard_new(void);

/**
 * Null when the clipboard holds no text, including when it holds an image.
 */
char *encre_clipboard_get_text(encre_ClipboardHandle handle);

int encre_clipboard_set_text(encre_ClipboardHandle handle, const char *text);

/**
 * Empties the clipboard, so a following simulated copy landing becomes observable.
 */
int encre_clipboard_clear(encre_ClipboardHandle handle);

int encre_clipboard_save(encre_ClipboardHandle handle);

int encre_clipboard_restore(encre_ClipboardHandle handle);

void encre_clipboard_free(encre_ClipboardHandle handle);

encre_HotkeyManagerHandle encre_hotkey_manager_new(void);

int encre_hotkey_clear(encre_HotkeyManagerHandle handle);

int encre_hotkey_register(encre_HotkeyManagerHandle handle,
                          const char *binding,
                          const char *action,
                          encre_HotkeyCallback callback);

/**
 * Push-to-talk: the callback receives 1 on key down and 0 on key up.
 */
int encre_hotkey_register_hold(encre_HotkeyManagerHandle handle,
                               const char *binding,
                               const char *action,
                               encre_PttCallback callback);

int encre_hotkey_start(encre_HotkeyManagerHandle handle);

int encre_hotkey_stop(encre_HotkeyManagerHandle handle);

/**
 * Null when the listener is running. The caller frees the string with `encre_free_string`.
 */
char *encre_hotkey_listen_error(encre_HotkeyManagerHandle handle);

void encre_hotkey_manager_free(encre_HotkeyManagerHandle handle);

encre_SimulatorHandle encre_simulator_new(void);

int encre_simulate_select_all(encre_SimulatorHandle handle);

int encre_simulate_copy(encre_SimulatorHandle handle);

int encre_simulate_paste(encre_SimulatorHandle handle);

/**
 * Drops modifiers the triggering hotkey left down. Call once before any combo.
 */
int encre_simulate_release_modifiers(encre_SimulatorHandle handle);

void encre_simulator_free(encre_SimulatorHandle handle);

encre_SttHandle encre_stt_new(encre_LevelCallback level);

void encre_stt_free(encre_SttHandle handle);

/**
 * Returns at once; a load failure is reported by the first transcription that needs it.
 */
int encre_stt_use_model(encre_SttHandle handle, const char *path);

int encre_stt_unload(encre_SttHandle handle);

int encre_stt_start(encre_SttHandle handle);

/**
 * Blocks for as long as inference takes; call it off the UI thread.
 */
char *encre_stt_stop(encre_SttHandle handle);

int encre_stt_cancel(encre_SttHandle handle);

/**
 * Null or empty means the system default. Takes effect on the next recording.
 */
int encre_stt_set_device(encre_SttHandle handle, const char *name);

/**
 * ISO code; NULL or empty asks the model to detect the language, which only some can.
 */
int encre_stt_set_language(encre_SttHandle handle, const char *code);

/**
 * While on, a take never touches the engine: `encre_stt_stop` fails and audio is
 * read back with `encre_stt_stop_pcm`. Takes effect on the next recording.
 */
int encre_stt_set_capture_only(encre_SttHandle handle, bool enabled);

/**
 * Headerless 16-bit signed little-endian mono PCM at `encre_SAMPLE_RATE`; free with
 * `encre_stt_free_bytes`. Null on failure; a silent take is a valid zero-length buffer.
 */
uint8_t *encre_stt_stop_pcm(encre_SttHandle handle, uintptr_t *out_len);

void encre_stt_free_bytes(uint8_t *ptr, uintptr_t len);

/**
 * Input device names, newline separated, the default marked with a leading '*'.
 */
char *encre_stt_devices(void);

#endif  /* ENCRE_FFI_H */
